# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


pool:
  vmImage: macOS-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'jfrog v2 extension ecosys'
    cliInstallationRepo: 'jfrog-cli-virtual'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: '$(Build.Repository.LocalPath)/testdata/mavenproject/pom.xml'
    goals: 'package'
    artifactoryResolverService: 'jfrog v2 extension ecosys'
    targetResolveReleaseRepo: 'maven-virtual'
    targetResolveSnapshotRepo: 'maven-virtual'

- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'jfrog v2 extension ecosys'
    imageName: 'ecosysjfrog.jfrog.io/docker-virtual/node:16-alpine3.17'
    collectBuildInfo: true
    buildName: 'docker-infra-images'
    buildNumber: 'cdpq-infra-docker-images'
    module: 'cdpq-node-16-alpine3.17'
    skipLogin: false
- task: JFrogAudit@1
  inputs:
    xrayConnection: 'xrayv2'
    watchesSource: 'none'
    licenses: false
    allowFailBuild: true
