# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
#- task: JFrogToolsInstaller@1
# inputs:
#   artifactoryConnection: 'jfrog v2 extension ecosys'
#   cliInstallationRepo: 'jfrog-cli-virtual'
# task: DockerInstaller@0
# inputs:
#   dockerVersion: '17.09.0-ce'

- task: JFrogDocker@1
  inputs:
    command: 'Pull'
    artifactoryConnection: 'jfrog v2 extension ecosys'
    imageName: 'ecosysjfrog.jfrog.io/docker-remote2/node:16-alpine3.16'
    collectBuildInfo: true
    buildName: 'docker-infra-images23'
    buildNumber: 'cdpq-infra-docker-images23'
    module: 'cdpq-node-16-alpine3.163'
    skipLogin: false
- task: JFrogAudit@1
  inputs:
    xrayConnection: 'xrayv2'
    watchesSource: 'none'
    licenses: false
    allowFailBuild: true
