# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'jfrog artifactory'
    cliInstallationRepo: 'jfrog-cli-virtual'
    installCustomVersion: true
    cliVersion: '2.19.0'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: '$(Build.Repository.LocalPath)/testdata/mavenproject/pom.xml'
    goals: 'package'
    artifactoryResolverService: 'jfrog artifactory'
    targetResolveReleaseRepo: 'maven-virtual'
    targetResolveSnapshotRepo: 'maven-virtual'
    
- task: JFrogMaven@1
  inputs:
    mavenPomFile: './testdata/mavenproject/pom.xml'
    goals: 'package'
    artifactoryResolverService: 'jfrog artifactory'
    targetResolveReleaseRepo: 'maven-virtual'
    targetResolveSnapshotRepo: 'maven-virtual'    

