# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'jfrog v2 extension ecosys'
    cliInstallationRepo: 'jfrog-cli-virtual'
    installCustomVersion: true
    cliVersion: '2.36.0'
    
- task: JFrogAudit@1
  inputs:
    xrayConnection: 'xrayv2'
    watchesSource: 'none'
    licenses: false
    allowFailBuild: true


- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'JFrog Platform V2'
    useCustomVersion: true
    cliVersion: '2.34.0'
    command: jf audit

- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'jfrog v2 extension ecosys'
    targetResolveReleaseRepo: 'maven-virtual'
    targetResolveSnapshotRepo: 'maven-virtual'
    artifactoryDeployService: 'jfrog v2 extension ecosys'
    targetDeployReleaseRepo: 'maven-virtual'
    targetDeploySnapshotRepo: 'maven-virtual'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    javaHomeOption: 'JDKVersion'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'jfrog v2 extension ecosys'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'