on: 
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,synchronize]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: Decathlon/release-notes-generator-action@v3.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
